version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Installing Docker..."
      - yum install -y docker
      - service docker start

  pre_build:
    commands:
      - echo "Running Python syntax check..."
      - python -m compileall -q -x 'venv|lib' . 2>&1 | tee syntax_check.log  # Syntax check with verbose logging, quiet mode to suppress listings
      - if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Syntax check failed in the following files:"; cat syntax_check.log; exit 1; fi  # Fail build if syntax check fails, print failures

  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover -s tests -p "*.py" -v || (echo "Unit tests failed"; exit 1)  # Combine test and failure check on same line
      - echo "Building epa_streamlit Docker image..."
      - docker build -t epa_streamlit .

  post_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050083327.dkr.ecr.us-east-1.amazonaws.com
      - echo "Tagging ECR image..."
      - docker tag epa_streamlit:latest 975050083327.dkr.ecr.us-east-1.amazonaws.com/epa_streamlit:latest
      - echo "Pushing Docker image to ECR..."
      - docker push 975050083327.dkr.ecr.us-east-1.amazonaws.com/epa_streamlit:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes